FROM node:22-alpine
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile
COPY worker ./worker
COPY src/lib/ai ./src/lib/ai
COPY tsconfig.json ./tsconfig.json
CMD ["pnpm","worker"]
