"use client";

import { useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Activity, AlertTriangle, ArrowDownRight, ArrowUpRight, Bell, Bookmark, Bot, BrainCircuit, BriefcaseBusiness, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Clock3, Command, Download, Filter, Gauge, GitFork, Globe2, Hash, LayoutDashboard, LifeBuoy, LineChart, ListFilter, Menu, MessageCircle, MoreHorizontal, Network, Plus, Search, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Target, Users, X } from "lucide-react";
import ModuleWorkspace from "@/components/module-workspace";

const nav = [
  { group: "WORKSPACE", items: [["Command Center", LayoutDashboard], ["Topics", Hash], ["Live Monitor", Activity], ["Conversation Explorer", MessageCircle]] },
  { group: "INTELLIGENCE", items: [["Narratives", GitFork], ["Entities", Users], ["Influencers", Users], ["Network Graph", Network], ["Competitors", BriefcaseBusiness], ["Sources", Globe2], ["Crisis Monitor", AlertTriangle]] },
  { group: "OPERATIONS", items: [["Alerts & Reports", Bell], ["AI Analyst", BrainCircuit], ["AI Control Center", Settings2], ["Connectors", Command], ["Admin", ShieldCheck]] },
];
const chartData = [
  { t: "08:00", mentions: 29, sentiment: 61 }, { t: "09:00", mentions: 36, sentiment: 58 }, { t: "10:00", mentions: 31, sentiment: 62 }, { t: "11:00", mentions: 53, sentiment: 57 }, { t: "12:00", mentions: 45, sentiment: 60 }, { t: "13:00", mentions: 66, sentiment: 54 }, { t: "14:00", mentions: 58, sentiment: 53 }, { t: "15:00", mentions: 86, sentiment: 48 }, { t: "16:00", mentions: 75, sentiment: 52 }, { t: "17:00", mentions: 103, sentiment: 49 }, { t: "18:00", mentions: 89, sentiment: 51 }, { t: "19:00", mentions: 126, sentiment: 46 },
];
const conversations = [
  { initials: "AD", color: "rose", name: "Ayu D. · @ayudaily", source: "X / Twitter", time: "2m", text: "Really hoping RIZPRAM addresses the delivery delays this week. My last order took 9 days and support hasn't replied yet.", tags: ["delivery delay", "customer support"], sentiment: "Negative", reach: "24.8K" },
  { initials: "RK", color: "blue", name: "Raka Kurniawan · @rakareviews", source: "Instagram", time: "7m", text: "Unboxing the new RIZPRAM essentials. Packaging is beautiful as always ✨ but the restock took forever.", tags: ["product quality", "restock"], sentiment: "Mixed", reach: "18.2K" },
  { initials: "MN", color: "violet", name: "Maya N. · @mayanoor", source: "TikTok", time: "11m", text: "This brand actually listened. The refill option is such a good move for sustainability 🌿", tags: ["sustainability", "refill"], sentiment: "Positive", reach: "42.6K" },
  { initials: "FP", color: "amber", name: "Fajar Putra · @fajarputra", source: "News / Online", time: "18m", text: "Growing consumer conversation around local beauty brands shifts toward transparent sourcing and faster fulfilment.", tags: ["category trends", "fulfilment"], sentiment: "Neutral", reach: "8.4K" },
];
const narratives = [{ title: "Delivery delays & fulfillment", share: "28%", change: "+34%", tone: "negative", posts: "1,284", bar: 83 }, { title: "New product launch reactions", share: "22%", change: "+18%", tone: "positive", posts: "1,012", bar: 67 }, { title: "Sustainability commitments", share: "17%", change: "+12%", tone: "positive", posts: "786", bar: 52 }, { title: "Customer service response time", share: "14%", change: "+41%", tone: "negative", posts: "645", bar: 44 }];
const pageHints: Record<string, string> = { "Topics": "Monitoring scope, query rules, and priority tracking.", "Live Monitor": "A real-time stream of public conversations from connected sources.", "Conversation Explorer": "Search, filter, and inspect individual conversations.", "Narratives": "Automatically clustered stories shaping the conversation.", "Entities": "People, brands, products, and places mentioned in your data.", "Influencers": "Authors ranked by reach, engagement, and narrative impact.", "Network Graph": "How key accounts and stories travel across communities.", "Competitors": "Share of voice and conversation shifts across brands.", "Sources": "Quality, coverage, and contribution by source.", "Alerts & Reports": "Scheduled briefings and threshold-based alerts.", "AI Analyst": "Ask evidence-grounded questions about your monitored data.", "AI Control Center": "Configure AI providers, model discovery, and task routing.", "Connectors": "Manage authorized source provider connections." };

export default function IntelligenceApp() {
  const [active, setActive] = useState("Command Center");
  const [range, setRange] = useState("Last 24 hours");
  const [search, setSearch] = useState("");
  const [showAlerts, setShowAlerts] = useState(false);
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState("");
  const [citations,setCitations]=useState<{id:string;url:string|null;source:string}[]>([]);
  const [busy, setBusy] = useState(false);
  const isHome = active === "Command Center";
  const filtered = useMemo(() => conversations.filter(x => `${x.name} ${x.text} ${x.tags.join(" ")}`.toLowerCase().includes(search.toLowerCase())), [search]);
  async function askAnalyst() {
    if (!question.trim()) return;
    setBusy(true);
    try { const response = await fetch("/api/ask", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question }) }); const data = await response.json(); setAnswer(data.answer || data.error || "No response."); setCitations(data.citations??[]); }
    catch { setAnswer("The analyst service is not reachable right now."); setCitations([]); }
    finally { setBusy(false); }
  }
  return <div className="shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark"><span>R</span></div><div><b>RIZPRAM</b><small>INTELLIGENCE</small></div><button className="icon-button sidebar-collapse"><ChevronLeft size={15}/></button></div>
      <div className="workspace-switch"><div className="workspace-avatar">R</div><div className="workspace-label"><b>Rizpram Studio</b><small>Intelligence workspace</small></div><ChevronDown size={14} /></div>
      <button className="topic-select"><span className="live-dot"/><span><small>MONITORING TOPIC</small><b>RIZPRAM Brand Health</b></span><ChevronDown size={14}/></button>
      <nav>{nav.map(section => <section key={section.group}><div className="nav-group">{section.group}</div>{section.items.map(([label, Icon]) => <button key={label as string} onClick={() => setActive(label as string)} className={`nav-item ${active === label ? "active" : ""}`}><Icon size={17}/><span>{label as string}</span>{label === "Alerts & Reports" && <i className="nav-count">3</i>}</button>)}</section>)}</nav>
      <div className="sidebar-bottom"><button className="nav-item" onClick={() => setActive("Settings")}><Settings2 size={17}/><span>Settings</span></button><button className="nav-item"><CircleHelp size={17}/><span>Help center</span></button><div className="profile"><div className="profile-pic">RP</div><div><b>Rizki Pramudya</b><small>Workspace admin</small></div><MoreHorizontal size={18}/></div></div>
    </aside>
    <main className="main-area">
      <header className="topbar"><div className="crumb"><button className="mobile-menu"><Menu size={19}/></button><span>Workspace</span><ChevronRight size={14}/><b>{active}</b></div><div className="top-actions"><div className="env-pill"><span className="green-pip"/> Demo workspace</div><button className="icon-button" aria-label="Search"><Search size={18}/></button><button className="icon-button alert-trigger" onClick={() => setShowAlerts(!showAlerts)} aria-label="Alerts"><Bell size={18}/><i/></button><div className="top-avatar">RP</div></div>
        {showAlerts && <div className="alerts-popover"><strong>Recent alerts</strong><p><i className="alert-dot red"/> Negative sentiment crossed 35% <small>12 min ago</small></p><p><i className="alert-dot amber"/> Narrative velocity +34% <small>38 min ago</small></p><p><i className="alert-dot blue"/> Weekly brief is ready <small>2 hours ago</small></p><button onClick={() => {setActive("Alerts & Reports");setShowAlerts(false)}}>View all alerts <ChevronRight size={13}/></button></div>}
      </header>
      <div className="content">
        <div className="page-heading"><div><div className="eyebrow"><span className="live-dot"/> MONDAY, OCTOBER 5, 2026 <span className="eyedot">·</span> JAKARTA, WIB</div><h1>{isHome ? "Good evening, Rizki" : active}<span className="wave">{isHome ? "✦" : ""}</span></h1><p>{isHome ? "Here’s what’s happening across your brand conversation today." : pageHints[active] ?? "Workspace preferences, permissions, and audit history."}</p></div><div className="heading-actions"><div className="range-select"><Clock3 size={15}/><select value={range} onChange={e => setRange(e.target.value)}><option>Last 24 hours</option><option>Last 7 days</option><option>Last 30 days</option></select><ChevronDown size={13}/></div><button className="button-secondary"><Download size={15}/> Export</button><button className="button-primary" onClick={() => setActive("Topics")}><Plus size={16}/> New monitoring topic</button></div></div>
        {!isHome && <><section className="module-banner"><div className="module-icon"><Sparkles size={19}/></div><div><b>{active} intelligence</b><p>{pageHints[active] ?? "Workspace security, team roles, and administrative controls."} Synthetic seed data is illustrative until authorized sources are connected.</p></div><button className="button-secondary" onClick={() => setActive("Command Center")}>Open command center <ChevronRight size={14}/></button></section><ModuleWorkspace active={active}/></>}
        <section className="kpi-grid">
          <Kpi title="Total mentions" value="8,492" change="18.6%" up caption="vs. previous period" icon={MessageCircle} color="purple" spark="0,16 12,13 22,17 34,8 45,11 58,2 70,6 83,0" />
          <Kpi title="Potential reach" value="12.8M" change="24.3%" up caption="vs. previous period" icon={Users} color="blue" spark="0,17 13,15 23,10 35,13 47,6 58,8 68,3 83,0" />
          <Kpi title="Positive sentiment" value="62.4%" change="3.2%" up caption="vs. previous period" icon={Gauge} color="green" spark="0,16 11,18 23,10 35,12 46,8 57,12 70,5 83,0" />
          <Kpi title="Active narratives" value="24" change="4 new" up caption="in the last 24 hours" icon={GitFork} color="amber" spark="0,18 12,12 22,15 35,5 46,9 57,11 70,2 83,0" />
        </section>
        <section className="overview-grid">
          <div className="card volume-card"><div className="card-header"><div><h2>Conversation volume</h2><p>Mentions and sentiment over time</p></div><div className="chart-controls"><div className="legend"><span className="legend-dot violet"/> Mentions <span className="legend-dot mint"/> Sentiment</div><button className="mini-select">Hourly <ChevronDown size={12}/></button><button className="icon-button small"><MoreHorizontal size={17}/></button></div></div><div className="chart-summary"><b>8,492</b><span className="positive-copy"><ArrowUpRight size={14}/> 18.6%</span><small>mentions this period</small></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData} margin={{ top: 10, right: 6, left: -22, bottom: 0 }}><defs><linearGradient id="mentionFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#8171dc" stopOpacity={0.19}/><stop offset="95%" stopColor="#8171dc" stopOpacity={0}/></linearGradient><linearGradient id="sentimentFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#55c9ae" stopOpacity={0.13}/><stop offset="95%" stopColor="#55c9ae" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#eef0f5"/><XAxis dataKey="t" axisLine={false} tickLine={false} tick={{ fill: "#9298a8", fontSize: 10 }} dy={10}/><YAxis axisLine={false} tickLine={false} tick={{ fill: "#9298a8", fontSize: 10 }} ticks={[0,40,80,120,160]}/><Tooltip contentStyle={{ borderRadius: 10, border: "1px solid #eeeef3", boxShadow: "0 8px 20px #24305b12", fontSize: 12 }}/><Area type="monotone" dataKey="mentions" stroke="#8372dc" strokeWidth={2.3} fill="url(#mentionFill)"/><Area type="monotone" dataKey="sentiment" stroke="#55c9ae" strokeWidth={2} fill="url(#sentimentFill)"/></AreaChart></ResponsiveContainer></div><div className="chart-footnote"><span><i className="status-pip"/> Peak conversation at 19:00 WIB</span><span>Updated just now <span className="sync-pip"/></span></div></div>
          <div className="card sentiment-card"><div className="card-header"><div><h2>Sentiment & emotion</h2><p>Across all tracked conversations</p></div><button className="icon-button small"><MoreHorizontal size={17}/></button></div><div className="sentiment-score"><div><b>62.4%</b><span className="positive-copy"><ArrowUpRight size={13}/> 3.2%</span><small>net positive</small></div><div className="sentiment-ring"><div><b>62</b><small>score</small></div></div></div><div className="sentiment-bar"><i/><i/><i/></div><div className="sentiment-legend"><span><i className="dot-positive"/>Positive <b>62.4%</b></span><span><i className="dot-neutral"/>Neutral <b>23.1%</b></span><span><i className="dot-negative"/>Negative <b>14.5%</b></span></div><div className="emotion-block"><div className="emotion-head"><b>Leading emotions</b><span>Share of mentions</span></div><Emotion label="Trust" value={36} tone="purple"/><Emotion label="Joy" value={28} tone="mint"/><Emotion label="Frustration" value={19} tone="orange"/></div></div>
        </section>
        <section className="lower-grid">
          <div className="card narratives-card"><div className="card-header"><div><h2>Emerging narratives</h2><p>Automated story clusters <span className="ai-mini"><Sparkles size={10}/> AI CLUSTERED</span></p></div><button className="text-link" onClick={() => setActive("Narratives")}>View all <ChevronRight size={14}/></button></div><div className="narrative-list">{narratives.map((n, i) => <div className="narrative-row" key={n.title}><div className={`narrative-symbol n-${i}`}><Hash size={15}/></div><div className="narrative-main"><b>{n.title}</b><div className="narrative-meta">{n.posts} mentions <span>·</span> {n.share} share</div><div className="narrative-progress"><i className={`progress-${n.tone}`} style={{width: `${n.bar}%`}}/></div></div><div className="narrative-change"><b className={n.tone === "negative" ? "negative-copy" : "positive-copy"}><ArrowUpRight size={12}/>{n.change}</b><small>velocity</small></div></div>)}</div><button className="card-footer-link" onClick={() => setActive("Narratives")}>Explore narrative clusters <ChevronRight size={14}/></button></div>
          <div className="card alerts-card"><div className="card-header"><div><h2>Attention needed</h2><p>Signals that may need a closer look</p></div><span className="alert-number">3</span></div><div className="alert-item high"><div className="alert-icon"><AlertTriangle size={16}/></div><div className="alert-copy"><b>Delivery delays gaining momentum</b><p>Negative mentions up 34% in the last 3 hours</p><small><span className="severity high-sev"/> HIGH PRIORITY <span>·</span> 12 min ago</small></div><ChevronRight size={15}/></div><div className="alert-item medium"><div className="alert-icon"><LineChart size={16}/></div><div className="alert-copy"><b>Competitor share of voice shifted</b><p>GlowLab gained 8 points since yesterday</p><small><span className="severity med-sev"/> WATCH <span>·</span> 46 min ago</small></div><ChevronRight size={15}/></div><div className="alert-item info"><div className="alert-icon"><ShieldCheck size={16}/></div><div className="alert-copy"><b>Potential coordinated activity</b><p>Cluster of 19 accounts detected on X</p><small><span className="severity info-sev"/> INVESTIGATE <span>·</span> 1 hr ago</small></div><ChevronRight size={15}/></div><button className="card-footer-link" onClick={() => setActive("Alerts & Reports")}>Open alert center <ChevronRight size={14}/></button></div>
        </section>
        <section className="bottom-grid">
          <div className="card conversation-card"><div className="card-header"><div><h2>Live conversation</h2><p><span className="live-dot"/> 4 illustrative sources · Demo data</p></div><div className="conversation-tools"><div className="search-box"><Search size={14}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search conversations"/></div><button className="mini-select"><ListFilter size={13}/> Filters <span className="filter-count">2</span></button><button className="icon-button small"><MoreHorizontal size={17}/></button></div></div><div className="conversation-table"><div className="table-head"><span>CONVERSATION</span><span>SENTIMENT</span><span>REACH</span><span>TIME</span></div>{filtered.map(c => <div className="conversation-row" key={c.name}><div className="author-avatar"><span className={`avatar-${c.color}`}>{c.initials}</span><div className="conv-body"><div className="author-line"><b>{c.name}</b><span>·</span><small>{c.source}</small></div><p>{c.text}</p><div className="tag-line">{c.tags.map(t => <span key={t}>{t}</span>)}</div></div></div><div><span className={`sentiment-chip chip-${c.sentiment.toLowerCase()}`}><i/> {c.sentiment}</span></div><div className="reach-cell">{c.reach}</div><div className="time-cell">{c.time} ago</div><button className="bookmark-button" aria-label="Bookmark"><Bookmark size={15}/></button></div>)}</div><button className="card-footer-link" onClick={() => setActive("Conversation Explorer")}>Explore all conversations <ChevronRight size={14}/></button></div>
          <div className="card analyst-card"><div className="analyst-top"><div className="analyst-icon"><BrainCircuit size={17}/></div><div><h2>Ask AI Analyst</h2><p>Answers grounded in your data</p></div><span className="grounded-pill"><ShieldCheck size={11}/> SOURCED</span></div><div className="analyst-prompt"><span>✦</span> What’s driving the rise in negative mentions today?</div><div className="suggestion-row"><button onClick={() => setQuestion("What themes are growing fastest today?")}>Fast-growing themes <ArrowUpRight size={12}/></button><button onClick={() => setQuestion("Compare sentiment across platforms")}>Compare platforms <ChevronRight size={12}/></button></div><textarea value={question} onChange={e => setQuestion(e.target.value)} onKeyDown={e => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); askAnalyst(); } }} placeholder="Ask about your conversations..."/><div className="analyst-bottom"><span><ShieldCheck size={12}/> Based on 8,492 mentions</span><button disabled={busy} onClick={askAnalyst}>{busy ? "Thinking…" : <><Sparkles size={13}/> Ask analyst</>}</button></div>{answer && <div className="analyst-answer"><b>Analyst response</b><p>{answer}</p>{citations.filter(c=>c.url).length>0&&<div className="source-links"><b>Sources</b>{citations.filter(c=>c.url).map(c=><a key={c.id} href={c.url!} target="_blank" rel="noreferrer">[{c.id}] {c.source} <ArrowUpRight size={10}/></a>)}</div>}<small>Grounded in monitored conversation sample</small></div>}<div className="privacy-note"><ShieldCheck size={12}/> Your data stays within your workspace</div></div>
        </section>
        <footer className="page-footer"><span>RIZPRAM INTELLIGENCE <b>·</b> v1.0.0</span><span>Data refreshed just now <i className="sync-pip"/></span></footer>
      </div>
    </main>
  </div>;
}

function Kpi({title,value,change,up,caption,icon:Icon,color,spark}:{title:string;value:string;change:string;up:boolean;caption:string;icon:typeof Activity;color:string;spark:string}) { return <article className="card kpi-card"><div className="kpi-top"><span>{title}</span><i className={`kpi-icon ${color}`}><Icon size={16}/></i></div><div className="kpi-value">{value}</div><div className="kpi-bottom"><span className={up?"positive-copy":"negative-copy"}>{up?<ArrowUpRight size={13}/>:<ArrowDownRight size={13}/>} {change}</span><small>{caption}</small><svg className={`spark spark-${color}`} viewBox="0 0 84 22" preserveAspectRatio="none"><polyline points={spark} fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg></div></article>; }
function Emotion({label,value,tone}:{label:string;value:number;tone:string}) { return <div className="emotion-row"><span>{label}</span><div><i className={`emotion-${tone}`} style={{width:`${value*2.15}px`}}/></div><b>{value}%</b></div>; }
