"use client";
import {useEffect,useState,useMemo} from 'react';
import {AreaChart,Area,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts';
import AiControlCenter from './ai-control-center';
type Row=Record<string,any>;
type Data={topics:Row[];topic?:Row;role:string;conversations:Row[];narratives:Row[];metrics:Row[];alerts:Row[];reports:Row[];edges:Row[];connectors:Row[];audit:Row[];coverage?:string};
const date=(v:string)=>new Date(v).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'});
const analysis=(p:Row)=>Array.isArray(p.conversation_analyses)?p.conversation_analyses[0]??{}:p.conversation_analyses??{};
function download(name:string,value:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
function Table({rows,columns}:{rows:Row[];columns:[string,string][]}){return <div style={{overflowX:'auto'}}><table className="live-table"><thead><tr>{columns.map(([key,label])=><th key={key}>{label}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id??i}>{columns.map(([k])=><td key={k}>{typeof r[k]==='object'?JSON.stringify(r[k]):String(r[k]??'—')}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="synthetic-note">No collected records yet.</p>}</div>}
export default function LiveWorkspace(){
 const [active,setActive]=useState('Command Center'),[data,setData]=useState<Data|null>(null),[topic,setTopic]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[sentiment,setSentiment]=useState(''),[question,setQuestion]=useState(''),[answer,setAnswer]=useState<Row|null>(null),[position,setPosition]=useState(100),[playing,setPlaying]=useState(false),[refresh,setRefresh]=useState(0);
 useEffect(()=>{const c=new AbortController();fetch('/api/workspace'+(topic?'?topic='+encodeURIComponent(topic):''),{signal:c.signal}).then(async r=>{const v=await r.json();if(!r.ok)throw Error(v.error);return v;}).then(v=>{setData(v);setError('');}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return ()=>c.abort();},[topic,refresh]);
 useEffect(()=>{const t=setInterval(()=>setRefresh(x=>x+1),15000);return ()=>clearInterval(t);},[]);
 useEffect(()=>{if(!playing)return;const t=setInterval(()=>setPosition(p=>{if(p>=100){setPlaying(false);return 100;}return p+1;}),200);return ()=>clearInterval(t);},[playing]);
 const posts=useMemo(()=>data?.conversations.filter(p=>(!search||p.content.toLowerCase().includes(search.toLowerCase()))&&(!sentiment||analysis(p).sentiment===sentiment))??[],[data,search,sentiment]);
 async function action(url:string,body:Row){setBusy(true);setError('');try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw Error(v.error??'Request failed');setRefresh(x=>x+1);return v;}catch(e){setError(e instanceof Error?e.message:'Request failed');}finally{setBusy(false);}}
 const names=['Command Center','Topics','Live Monitor','Conversation Explorer','Narratives','Entities','Influencers','Network Graph','Competitors','Sources','Crisis Monitor','Alerts & Reports','AI Analyst','AI Control Center','Connectors','Admin'];
 const c=data?.conversations??[];const analyzed=c.filter(p=>analysis(p).sentiment);const negative=analyzed.filter(p=>analysis(p).sentiment==='negative').length;const now=Date.now();const current=c.filter(p=>Date.parse(p.published_at)>now-3600000).length,previous=c.filter(p=>Date.parse(p.published_at)>now-7200000&&Date.parse(p.published_at)<=now-3600000).length;
 const sources=Object.entries(c.reduce((r:Row,p)=>({...r,[p.source]:(r[p.source]??0)+1}),{})).map(([source,count])=>({source,count}));
 const people=Object.values(c.reduce((r:Row,p)=>{const k=p.source+':'+p.author_id;const old=r[k]??{author:p.author_name,source:p.source,posts:0,engagement:0};r[k]={...old,posts:old.posts+1,engagement:old.engagement+Number(p.engagement)};return r;},{})).sort((a:Row,b:Row)=>b.engagement-a.engagement);
 const entities=Object.values(c.reduce((r:Row,p)=>{for(const e of analysis(p).entities??[]){const k=e.type+':'+e.name;const old=r[k]??{name:e.name,type:e.type,mentions:0};r[k]={...old,mentions:old.mentions+1};}return r;},{}));
 return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">R</div><div><b>RIZPRAM</b><small>INTELLIGENCE</small></div></div><div className="workspace-switch"><b>Intelligence workspace</b></div><nav>{names.map(n=><button key={n} className={'nav-item '+(active===n?'active':'')} onClick={()=>setActive(n)}>{n}</button>)}</nav><div className="sidebar-bottom"><a href="/login">Account</a></div></aside><main className="main-area"><header className="topbar"><b>{active}</b><span className="env-pill">{data?.topic?.demo_mode?'Synthetic seeded topic':'Connected workspace'}</span></header><div className="content"><div className="page-heading"><div><h1>{active}</h1><p>{data?.coverage??'Loading workspace…'}</p></div><select aria-label="Monitoring topic" value={topic||data?.topic?.id||''} onChange={e=>{setTopic(e.target.value);setAnswer(null);setPosition(100);}}>{data?.topics.map(t=><option key={t.id} value={t.id}>{t.name}{t.demo_mode?' · DEMO':''}</option>)}</select></div>{error&&<p role="alert" className="crisis-callout">{error}</p>}{data?.topic?.demo_mode&&<p className="synthetic-note">SYNTHETIC DEMO: these seeded conversations are illustrative, not live public evidence.</p>}
 {!data?<p>Loading…</p>:<>
 {active==='AI Control Center'?<AiControlCenter/>:active==='Topics'?<section className="card live-panel"><Table rows={data.topics} columns={[["name","Topic"],["query","Query"],["is_active","Active"],["demo_mode","Demo"]]}/>{data.role!=='viewer'&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await action('/api/workspace',{name:f.get('name'),keywords:f.get('keywords')});}} className="inline-create"><input name="name" required placeholder="Topic name"/><input name="keywords" required placeholder="Keywords, comma separated"/><button disabled={busy} className="button-primary">Create monitoring topic</button></form>}</section>:
 active==='Command Center'?<><section className="kpi-grid">{[['Collected sample',c.length],['Analyzed',analyzed.length],['Negative share',analyzed.length?Math.round(negative/analyzed.length*100)+'%':'—'],['Hourly velocity',previous?(current/previous).toFixed(2)+'×':'No baseline']].map(([label,value])=><article className="card kpi-card" key={label}><p>{label}</p><div className="kpi-value">{value}</div><small>Current collected sample</small></article>)}</section><section className="card live-panel"><h2>Hourly conversation volume</h2><div style={{height:260}}><ResponsiveContainer><AreaChart data={data.metrics.map(m=>({...m,time:date(m.bucket_at)}))}><XAxis dataKey="time"/><YAxis/><Tooltip/><Area dataKey="mention_count" stroke="#8372dc" fill="#eae5fb"/></AreaChart></ResponsiveContainer></div></section><section className="card live-panel"><h2>Sentiment, emotion, stance & intent</h2><Table rows={analyzed.map(p=>({...analysis(p),author:p.author_name}))} columns={[["author","Author"],["sentiment","Sentiment"],["emotions","Emotion"],["stance","Stance"],["intent","Intent"]]}/></section></>:
 ['Conversation Explorer','Live Monitor'].includes(active)?<section className="card live-panel"><div className="conversation-tools"><input aria-label="Search conversations" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search conversations"/><select aria-label="Sentiment filter" value={sentiment} onChange={e=>setSentiment(e.target.value)}><option value="">All sentiment</option>{['positive','negative','neutral','mixed'].map(s=><option key={s}>{s}</option>)}</select><button className="button-secondary" onClick={()=>download('intel-conversations.json',posts)}>Export sample</button></div>{posts.map(p=><article className="live-post" key={p.id}><b>{p.author_name??'Unknown author'} · {p.source}</b><small>{date(p.published_at)}</small><p>{p.content}</p><span className={'sentiment-chip chip-'+(analysis(p).sentiment??'neutral')}>{analysis(p).sentiment??'Pending analysis'}</span>{p.canonical_url?.startsWith('https://')&&!data.topic?.demo_mode&&<a href={p.canonical_url} target="_blank" rel="noreferrer"> Source record ↗</a>}</article>)}{!posts.length&&<p>No matching conversations.</p>}</section>:
 active==='Narratives'?<section className="card live-panel"><Table rows={data.narratives} columns={[["title","Narrative"],["summary","Summary"],["post_count","Posts"],["sentiment","Sentiment"],["velocity","Stored velocity"],["risk_score","Risk score"]]}/></section>:
 active==='Entities'?<section className="card live-panel"><Table rows={entities} columns={[["name","Entity"],["type","Type"],["mentions","Sample mentions"]]}/></section>:
 active==='Influencers'?<section className="card live-panel"><p>Observed engagement ranking in this sample; this does not establish causal influence.</p><Table rows={people} columns={[["author","Author"],["source","Source"],["posts","Posts"],["engagement","Engagement"]]}/></section>:
 ['Sources','Connectors'].includes(active)?<section className="card live-panel"><h2>Collected source coverage</h2><Table rows={sources} columns={[["source","Source"],["count","Sample posts"]]}/><h2>Authorized connectors</h2><button className="button-primary" disabled={busy||data.role==='viewer'} onClick={()=>action('/api/sync',{topic_id:data.topic?.id})}>Queue source ingestion</button><Table rows={data.connectors} columns={[["display_name","Connector"],["state","State"],["last_sync_at","Last sync"],["last_error","Error"]]}/><p>Provider credentials and API endpoints are configured server-side. No connector is live until authorization and ingestion are verified.</p></section>:
 active==='Network Graph'?<section className="card live-panel"><Network edges={data.edges} position={position}/><div className="timeline-controls"><button onClick={()=>{if(position===100)setPosition(0);setPlaying(!playing);}}>{playing?'Pause':'Play'}</button><input aria-label="Network timeline" type="range" min="0" max="100" value={position} onChange={e=>setPosition(Number(e.target.value))}/><span>{position}%</span></div><p>Only recorded propagation edges are displayed. Missing edges indicate incomplete source coverage.</p></section>:
 active==='Crisis Monitor'?<section className="card live-panel"><Table rows={data.alerts} columns={[["title","Signal"],["summary","Evidence summary"],["severity","Severity"],["status","Status"],["triggered_at","Triggered"]]}/></section>:
 active==='Alerts & Reports'?<section className="card live-panel"><button disabled={busy||data.role==='viewer'||!data.topic} className="button-primary" onClick={()=>action('/api/reports',{title:'Topic intelligence brief',format:'json',topic_id:data.topic?.id})}>Generate evidence report</button><Table rows={data.alerts} columns={[["title","Alert"],["severity","Severity"],["status","Status"]]}/>{data.reports.map(r=><div className="live-post" key={r.id}><b>{r.title}</b> · {r.status} · {date(r.created_at)} {r.status==='ready'&&<button className="button-secondary" onClick={()=>download('intel-report-'+r.id+'.json',r.content)}>Download JSON</button>}</div>)}</section>:
 active==='AI Analyst'?<section className="card live-panel"><h2>Ask from collected evidence</h2><textarea aria-label="Analyst question" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What is driving negative conversation?"/><button disabled={busy||!question.trim()} className="button-primary" onClick={async()=>{const v=await action('/api/ask',{question,topic_id:data.topic?.id});if(v)setAnswer(v);}}>Ask analyst</button>{answer&&<div className="live-post"><p style={{whiteSpace:'pre-wrap'}}>{answer.answer}</p>{answer.citations?.map((s:Row)=><p key={s.id}>{s.url?<a href={s.url} target="_blank" rel="noreferrer">[{s.id}] {s.source}</a>:<span>[{s.id}] {s.source} (no public URL)</span>}</p>)}</div>}</section>:
 active==='Admin'?<section className="card live-panel"><p>Your role: {data.role}. Member creation is managed through Supabase Auth.</p><Table rows={data.audit} columns={[["action","Action"],["resource_type","Resource"],["created_at","Time"],["details","Details"]]}/></section>:
 <section className="card live-panel"><p>Competitor comparison requires separately configured monitoring topics with comparable source coverage.</p><Table rows={data.topics} columns={[["name","Topic"],["query","Query"],["is_active","Active"]]}/></section>}
 </>}</div></main></div>;
}
function Network({edges,position}:{edges:Row[];position:number}){
 const times=edges.map(e=>Date.parse(e.occurred_at));const min=Math.min(...times),max=Math.max(...times);const end=min+(max-min)*position/100;const visible=edges.filter(e=>Date.parse(e.occurred_at)<=end);const authors=[...new Set(edges.flatMap(e=>[e.from_author_id,e.to_author_id]))].slice(0,100);const nodes=authors.map((id,i)=>({id,x:350+Math.cos(i/authors.length*Math.PI*2)*240,y:160+Math.sin(i/authors.length*Math.PI*2)*120}));
 return <><h2>Propagation · {visible.length} recorded edges</h2>{!edges.length?<p>No observed propagation relationships in this topic yet.</p>:<svg viewBox="0 0 700 320" role="img" aria-label="Observed propagation network">{visible.map(e=>{const a=nodes.find(n=>n.id===e.from_author_id),b=nodes.find(n=>n.id===e.to_author_id);return a&&b?<line key={e.id} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke="#b9aedf"><title>{e.edge_type} · {date(e.occurred_at)}</title></line>:null;})}{nodes.filter(n=>visible.some(e=>e.from_author_id===n.id||e.to_author_id===n.id)).map(n=><g key={n.id}><circle cx={n.x} cy={n.y} r="7" fill="#8372dc"/><text x={n.x+10} y={n.y} fontSize="9">{n.id.slice(0,18)}</text></g>)}</svg>}</>;
}
