"use client";

import { useEffect, useState } from "react";
import { Activity, AlertTriangle, ArrowUpRight, CheckCircle2, ChevronRight, Clock3, Download, KeyRound, Play, Plus, Settings2, ShieldCheck, Sparkles, Users, Pause } from "lucide-react";
import AiControlCenter from "@/components/ai-control-center";

const demos = {
  Topics: [["RIZPRAM Brand Health","Active · 6 sources","8,492","Oct 5, 2026"],["RIZPRAM Product Launch","Active · 4 sources","2,104","Oct 4, 2026"],["Industry & category pulse","Paused · 3 sources","6,218","Oct 1, 2026"]],
  Influencers: [["Maya Noor","TikTok · 42.6K reach","0.84","Sustainability advocate"],["Ayu Daily","X · 24.8K reach","0.78","Customer voice"],["Raka Reviews","Instagram · 18.2K reach","0.72","Beauty reviewer"]],
  Competitors: [["RIZPRAM","Brand health","38.4%","+4.2 pts"],["GlowLab","Competitor","27.1%","+8.0 pts"],["NaturaHouse","Competitor","19.6%","−1.3 pts"]],
  Sources: [["X API","Authorized API · Disconnected","2,184","Not configured"],["Meta Graph API","Authorized API · Disconnected","3,116","Not configured"],["TikTok Business API","Authorized API · Disconnected","1,920","Not configured"],["News provider","Authorized feed · Disconnected","1,272","Not configured"]],
};

export default function ModuleWorkspace({ active }: { active: string }) {
  const [position,setPosition]=useState(35); const [playing,setPlaying]=useState(false); const [newTopic,setNewTopic]=useState(false); const [draft,setDraft]=useState(""); const [topics,setTopics]=useState(demos.Topics); const [reportStatus,setReportStatus]=useState("");
  useEffect(()=>{ if(!playing) return; const t=setInterval(()=>setPosition(p=>p>=100?0:p+1),180); return ()=>clearInterval(t); },[playing]);
  async function generateReport(){setReportStatus("Queueing report…");try{const response=await fetch("/api/reports",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:"Daily brand pulse",format:"pdf"})});const data=await response.json();setReportStatus(response.ok?(data.demo?"Demo report queued · connect sources for a real evidence report":"Report queued · processing will complete in the background"):(data.error??"Report could not be queued."));}catch{setReportStatus("Report service is not reachable right now.");}}
  if(active==="Topics") return <section className="module-workspace"><div className="card module-table"><div className="module-table-head"><div><h2>Monitoring topics</h2><p>Each topic keeps query rules, coverage, and analysis in its own scope.</p></div><button className="button-primary" onClick={()=>setNewTopic(!newTopic)}><Plus size={14}/> New topic</button></div>{newTopic&&<form className="inline-create" onSubmit={e=>{e.preventDefault();if(draft.trim()){setTopics([[draft,"Draft · no sources","0","Just now"],...topics]);setDraft("");setNewTopic(false);}}}><input required value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Topic name"/><input placeholder="Keywords or phrases"/><button className="button-primary">Create demo topic</button></form>}<div className="module-grid-head"><span>TOPIC</span><span>STATUS</span><span>MENTIONS</span><span>UPDATED</span></div>{topics.map(t=><div className="module-data-row" key={t[0]}><b>{t[0]}</b><span><i className={t[1].startsWith("Active")?"row-live":"row-idle"}/>{t[1]}</span><span>{t[2]}</span><span>{t[3]}</span></div>)}</div><p className="synthetic-note"><ShieldCheck size={13}/> Demo values are synthetic. Provider feeds require an authorized connection.</p></section>;
  if(active==="Network Graph") return <section className="module-workspace"><div className="card graph-card"><div className="module-table-head"><div><h2>Propagation network</h2><p>Illustrative account-to-account spread · timeline playback</p></div><span className="synthetic-tag">SYNTHETIC DEMO</span></div><div className="network-stage"><svg viewBox="0 0 700 280" role="img" aria-label="Synthetic conversation propagation graph"><g className="edges"><path d="M350 126 175 65M350 126 170 200M350 126 535 54M350 126 535 206M175 65 92 123M175 65 252 28M170 200 74 238M170 200 265 254M535 54 621 112M535 54 440 20M535 206 630 244M535 206 445 258"/><path d="M175 65 170 200M535 54 535 206" className="edge-faint"/></g><g className="nodes"><circle cx="350" cy="126" r="31" className="node-main"/><text x="350" y="122">RIZPRAM</text><text x="350" y="137" className="node-sub">TOPIC</text><circle cx="175" cy="65" r="21" className="node-violet"/><text x="175" y="69">Ayu D.</text><circle cx="170" cy="200" r="17" className="node-mint"/><text x="170" y="204">Maya N.</text><circle cx="535" cy="54" r="23" className="node-blue"/><text x="535" y="58">Raka R.</text><circle cx="535" cy="206" r="19" className="node-amber"/><text x="535" y="210">GlowLab</text><circle cx="92" cy="123" r="11" className="node-small"/><circle cx="252" cy="28" r="10" className="node-small"/><circle cx="74" cy="238" r="9" className="node-small"/><circle cx="265" cy="254" r="11" className="node-small"/><circle cx="621" cy="112" r="10" className="node-small"/><circle cx="440" cy="20" r="9" className="node-small"/><circle cx="630" cy="244" r="10" className="node-small"/><circle cx="445" cy="258" r="8" className="node-small"/></g></svg><div className="graph-label"><i/> conversation spread <span>·</span> 14 accounts <span>·</span> 12 interactions</div></div><div className="timeline-controls"><button onClick={()=>setPlaying(!playing)} aria-label={playing?"Pause":"Play"}>{playing?<Pause size={15}/>:<Play size={15}/>}</button><span>08:00</span><input type="range" min="0" max="100" value={position} onChange={e=>setPosition(Number(e.target.value))}/><span>20:00 WIB</span><b>{String(8+Math.floor(position*12/100)).padStart(2,"0")}:{String(position%6*10).padStart(2,"0")}</b></div></div></section>;
  if(active==="Connectors") return <section className="module-workspace"><div className="connector-grid">{["X API","Meta Graph API","TikTok Business API","News & web provider"].map((name,i)=><article className="card connector-card" key={name}><div className="connector-logo">{["𝕏","◎","♪","N"][i]}</div><div className="connector-title"><b>{name}</b><small>Official / authorized API</small></div><span className="connector-state"><i/> Disconnected</span><p>Connect an authorized provider account. Credentials belong in a secret store; the application never scrapes public pages.</p><button className="button-secondary" onClick={()=>alert("Connector setup uses the provider OAuth flow and a server-side secret reference. Add credentials after deployment.")}><KeyRound size={13}/> Configure authorization</button></article>)}</div><p className="synthetic-note"><ShieldCheck size={13}/> AI provider setup and model routing are managed in AI Control Center.</p></section>;
  if(active==="AI Control Center") return <AiControlCenter/>;
  if(active==="Network Graph") return null;
  if(active==="Admin") return <section className="module-workspace admin-grid"><div className="card module-table"><div className="module-table-head"><div><h2>Workspace members</h2><p>Role-based access is enforced in Postgres row policies.</p></div><button className="button-secondary"><Users size={13}/> Invite member</button></div><div className="module-grid-head"><span>MEMBER</span><span>ROLE</span><span>STATUS</span><span>LAST ACTIVE</span></div>{[["Rizki Pramudya","Owner","Active","Now"],["Intelligence team","Analyst","Active","Today"],["Leadership group","Viewer","Invited","—"]].map(m=><div className="module-data-row" key={m[0]}><b>{m[0]}</b><span>{m[1]}</span><span><i className={m[2]==="Active"?"row-live":"row-idle"}/>{m[2]}</span><span>{m[3]}</span></div>)}</div><div className="card audit-card"><h2>Recent audit activity</h2><p>Workspace access and configuration events</p>{[["Topic configuration viewed","Rizki Pramudya","2m ago"],["Report export prepared","Intelligence team","1h ago"],["AI provider settings opened","Rizki Pramudya","Yesterday"]].map(x=><div className="audit-row" key={x[0]}><ShieldCheck size={15}/><div><b>{x[0]}</b><small>{x[1]} · {x[2]}</small></div></div>)}</div></section>;
  if(active==="Alerts & Reports") return <section className="module-workspace report-grid"><div className="card report-card"><div className="module-table-head"><div><h2>Generate intelligence report</h2><p>Create a source-linked brief for a monitoring topic.</p></div><Download size={17}/></div><label>Report template<select><option>Daily brand pulse</option><option>Narrative risk brief</option><option>Competitor comparison</option><option>Source performance</option></select></label><label>Time window<select><option>Last 24 hours</option><option>Last 7 days</option><option>Last 30 days</option></select></label><label>Include modules<select><option>All intelligence modules</option><option>Sentiment, narratives, and alerts</option></select></label><button className="button-primary" onClick={generateReport}><Sparkles size={14}/> Generate report</button>{reportStatus&&<div className="report-ready"><CheckCircle2 size={16}/>{reportStatus}<span>Reports are generated in the background using source-linked evidence.</span></div>}</div><div className="card audit-card"><h2>Alert rules</h2><p>Crisis detection and momentum thresholds</p>{[["Negative sentiment exceeds 30%","High priority"],["Narrative velocity rises 25%","Watch"],["Coordinated activity score above 80","Investigate"]].map(x=><div className="audit-row" key={x[0]}><AlertTriangle size={15}/><div><b>{x[0]}</b><small>{x[1]} · Demo rule</small></div></div>)}</div></section>;
  if(active==="Crisis Monitor") return <section className="module-workspace"><div className="crisis-callout"><div><AlertTriangle size={20}/></div><section><b>Elevated narrative risk · Delivery delays</b><p>Synthetic demo signal only: negative mentions increased alongside faster discussion velocity. Validate against connected source evidence before action.</p></section><span>HIGH</span></div><div className="crisis-stats"><div className="card"><small>RISK SCORE</small><b>76<span>/100</span></b><p>Demo score</p></div><div className="card"><small>MENTION VELOCITY</small><b>+34%</b><p>vs. prior window</p></div><div className="card"><small>NEGATIVE SHARE</small><b>38.2%</b><p>synthetic sample</p></div><div className="card"><small>SPREAD</small><b>3 sources</b><p>demo connectors</p></div></div></section>;
  if(active==="AI Analyst") return <section className="module-workspace"><div className="card analyst-page"><div className="analyst-icon"><Sparkles size={18}/></div><h2>Evidence-grounded analysis</h2><p>The server retrieves recent posts from your active topic and asks the configured AI gateway to cite the records it used. Configure the gateway before enabling production answers.</p><div className="grounding-steps"><span>1 <b>Retrieve topic evidence</b></span><ChevronRight size={15}/><span>2 <b>Analyze with provider</b></span><ChevronRight size={15}/><span>3 <b>Return source links</b></span></div></div></section>;
  if(active==="Settings") return <section className="module-workspace"><div className="card report-card"><div className="module-table-head"><div><h2>Workspace settings</h2><p>Dedicated app and database configuration.</p></div><Settings2 size={18}/></div><div className="settings-check"><CheckCircle2 size={15}/> Dedicated app service name <b>rizpram-intelligence</b></div><div className="settings-check"><CheckCircle2 size={15}/> Isolated web port <b>127.0.0.1:3210</b></div><div className="settings-check"><Clock3 size={15}/> Production Supabase project <b>Isolated project configured</b></div><small>Secrets are injected from the server environment; no service-role key is exposed to the browser.</small></div></section>;
  const rows=(demos as any)[active];
  if(rows) return <section className="module-workspace"><div className="card module-table"><div className="module-table-head"><div><h2>{active} overview</h2><p>Synthetic demo values pending authorized source ingestion.</p></div><button className="button-secondary"><Download size={13}/> Export view</button></div><div className="module-grid-head"><span>{active==="Sources"?"SOURCE":active==="Influencers"?"ACCOUNT":"NAME"}</span><span>TYPE / COVERAGE</span><span>{active==="Competitors"?"SHARE OF VOICE":"METRIC"}</span><span>CHANGE / STATUS</span></div>{rows.map((r:string[])=><div className="module-data-row" key={r[0]}><b>{r[0]}</b><span>{r[1]}</span><span>{r[2]}</span><span>{r[3]}</span></div>)}</div></section>;
  return <section className="module-workspace"><div className="card module-table"><div className="module-table-head"><div><h2>{active} workspace</h2><p>Analysis is scoped to your selected topic.</p></div><Activity size={17}/></div><div className="empty-module"><Sparkles size={18}/><b>Intelligence view</b><p>Connect an authorized source to populate real signals. Synthetic sample data remains labeled in demo mode.</p><button className="button-secondary">Configure data source <ChevronRight size={13}/></button></div></div></section>;
}
